"""add task attention and delay risk

Revision ID: 041820b47cec
Revises: 2b24f3d4295a
Create Date: 2026-05-27 18:08:57.413895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041820b47cec'
down_revision: Union[str, Sequence[str], None] = '2b24f3d4295a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('is_internal',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attention_required', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('delay_risk', sa.Enum('low', 'medium', 'high', name='delayriskenum'), nullable=False, server_default=sa.text("'low'")))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('delay_risk')
        batch_op.drop_column('attention_required')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('is_internal',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###

