"""Phase 8: SLA and Workflow enhancements

Revision ID: 2ef9862dd746
Revises: 041820b47cec
Create Date: 2026-06-01 08:08:35.232942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef9862dd746'
down_revision: Union[str, Sequence[str], None] = '041820b47cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegator_id', sa.Integer(), nullable=False),
    sa.Column('delegatee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['delegatee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_delegations_delegatee_id'), ['delegatee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_delegations_delegator_id'), ['delegator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_delegations_id'), ['id'], unique=False)

    op.create_table('sla_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('allowed_hours', sa.Integer(), nullable=False),
    sa.Column('escalation_enabled', sa.Boolean(), nullable=False),
    sa.Column('escalation_after_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_rules_id'), ['id'], unique=False)

    op.create_table('approval_escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('escalated_from', sa.Integer(), nullable=False),
    sa.Column('escalated_to', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['escalated_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_escalations_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_escalations_escalated_from'), ['escalated_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_escalations_escalated_to'), ['escalated_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_escalations_id'), ['id'], unique=False)

    op.create_table('sla_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('sla_rule_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('breach_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sla_rule_id'], ['sla_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_tracking_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sla_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_tracking_id'))

    op.drop_table('sla_tracking')
    with op.batch_alter_table('approval_escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_escalations_id'))
        batch_op.drop_index(batch_op.f('ix_approval_escalations_escalated_to'))
        batch_op.drop_index(batch_op.f('ix_approval_escalations_escalated_from'))
        batch_op.drop_index(batch_op.f('ix_approval_escalations_approval_id'))

    op.drop_table('approval_escalations')
    with op.batch_alter_table('sla_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_rules_id'))

    op.drop_table('sla_rules')
    with op.batch_alter_table('approval_delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_delegations_id'))
        batch_op.drop_index(batch_op.f('ix_approval_delegations_delegator_id'))
        batch_op.drop_index(batch_op.f('ix_approval_delegations_delegatee_id'))

    op.drop_table('approval_delegations')
    # ### end Alembic commands ###

