"""Add notification preferences and SLA audit enhancements

Revision ID: bed9fa82a9ae
Revises: 2ef9862dd746
Create Date: 2026-06-01 20:40:31.469490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed9fa82a9ae'
down_revision: Union[str, Sequence[str], None] = '2ef9862dd746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('task_notifications', sa.Boolean(), nullable=False),
    sa.Column('approval_notifications', sa.Boolean(), nullable=False),
    sa.Column('escalation_notifications', sa.Boolean(), nullable=False),
    sa.Column('document_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sla_due_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_escalated', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('current_escalation_to', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_approvals_current_escalation_to'), ['current_escalation_to'], unique=False)
        batch_op.create_foreign_key('fk_approvals_current_escalation_to', 'users', ['current_escalation_to'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('module_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('record_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('old_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('new_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=50), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sla_due_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_sla_breached', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('is_sla_breached')
        batch_op.drop_column('sla_due_time')
        batch_op.drop_column('sla_status')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('notification_type')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('new_data')
        batch_op.drop_column('old_data')
        batch_op.drop_column('record_id')
        batch_op.drop_column('module_name')
        batch_op.drop_column('action_type')

    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_approvals_current_escalation_to', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_approvals_current_escalation_to'))
        batch_op.drop_column('current_escalation_to')
        batch_op.drop_column('is_escalated')
        batch_op.drop_column('sla_due_time')
        batch_op.drop_column('sla_status')

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_preferences_id'))

    op.drop_table('notification_preferences')
    # ### end Alembic commands ###

